package oe;

import java.io.Serializable;

/**
 * Represents a customer in the system. This class serves as the base class
 * for all customer types and implements Serializable to allow object serialization.
 *
 * <p>The class maintains a static counter for automatic customer ID generation
 * and stores basic customer information including name, address, and phone number.
 *
 * <p>Example usage:
 * <pre>
 * Customer cust = new Customer("John Doe", "123 Main St", "555-1234");
 * </pre>
 *
 * @author [Your Name]
 * @version 1.0
 * @see Company
 * @see Serializable
 */
public class Customer implements Serializable {
    /**
     * The unique identifier for this customer
     */
    private int id;
    
    /**
     * The name of the customer
     */
    private String name;
    
    /**
     * The address of the customer
     */
    private String address;
    
    /**
     * The phone number of the customer
     */
    private String phone;

    /**
     * Static counter for generating unique customer IDs.
     * Incremented each time a new Customer is created.
     */
    private static int nextCustId = 0;
    
    /**
     * Default constructor that initializes a customer with auto-generated ID.
     * The ID is generated by incrementing the static nextCustId counter.
     */
    public Customer() {
        nextCustId++;
        setId(nextCustId);
    }

    /**
     * Creates a customer with specified details and auto-generated ID.
     * 
     * @param name The name of the customer
     * @param address The address of the customer
     * @param phone The phone number of the customer
     */
    public Customer(String name, String address, String phone) {
        this();
        this.name = name;
        this.address = address;
        this.phone = phone;
    }

    /**
     * Sets the customer's ID.
     * 
     * @param id The unique identifier to set
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Sets the customer's name.
     * 
     * @param name The name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Sets the customer's address.
     * 
     * @param address The address to set
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * Sets the customer's phone number.
     * 
     * @param phone The phone number to set
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * Gets the customer's ID.
     * 
     * @return The customer's unique identifier
     */
    public int getId() {
        return id;
    }

    /**
     * Gets the customer's name.
     * 
     * @return The customer's name
     */
    public String getName() {
        return name;
    }

    /**
     * Gets the customer's address.
     * 
     * @return The customer's address
     */
    public String getAddress() {
        return address;
    }

    /**
     * Gets the customer's phone number.
     * 
     * @return The customer's phone number
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Gets the next available customer ID without creating a customer.
     * 
     * @return The next customer ID that will be assigned
     */
    public static int getNextCustId() {
        return nextCustId;
    }
    
    /**
     * Returns a string representation of the Customer object.
     * The format is: "[ClassName]id name address phone"
     * 
     * @return A string representation of the Customer
     */
    @Override
    public String toString() {
        return "[" + Util.getClassName(this) + "]" + id + " " + name + " " +
            address + " " + phone;
    }
}