package training.iqgateway;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="http://localhost:7101/Lesson08-JAXB-BottomUp-Project1-context-root/CurrencyConvertorPort/#%7Bhttp%3A%2F%2Fiqgateway.training%2F%7DCurrencyConvertorService?wsdl",
  targetNamespace="http://iqgateway.training/", name="CurrencyConvertor")
@XmlSeeAlso(
  { training.iqgateway.types.ObjectFactory.class })
public interface CurrencyConvertor
{
  @WebMethod
  @Action(input="", output="")
  @ResponseWrapper(localName="dollarToRsResponse", targetNamespace="http://iqgateway.training/",
    className="training.iqgateway.types.DollarToRsResponse")
  @RequestWrapper(localName="dollarToRs", targetNamespace="http://iqgateway.training/",
    className="training.iqgateway.types.DollarToRs")
  @WebResult(targetNamespace="")
  public double dollarToRs(@WebParam(targetNamespace="", name="arg0")
    double arg0);

  @WebMethod
  @Action(input="", output="")
  @ResponseWrapper(localName="eurosToRsResponse", targetNamespace="http://iqgateway.training/",
    className="training.iqgateway.types.EurosToRsResponse")
  @RequestWrapper(localName="eurosToRs", targetNamespace="http://iqgateway.training/",
    className="training.iqgateway.types.EurosToRs")
  @WebResult(targetNamespace="")
  public double eurosToRs(@WebParam(targetNamespace="", name="arg0")
    double arg0);

  @WebMethod
  @Action(input="", output="")
  @ResponseWrapper(localName="yensToRsResponse", targetNamespace="http://iqgateway.training/",
    className="training.iqgateway.types.YensToRsResponse")
  @RequestWrapper(localName="yensToRs", targetNamespace="http://iqgateway.training/",
    className="training.iqgateway.types.YensToRs")
  @WebResult(targetNamespace="")
  public double yensToRs(@WebParam(targetNamespace="", name="arg0")
    double arg0);
}
